name: Generate Snake

on:
  schedule: # Runs at 12am UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user: karansquad
          outputs: dist/snake.svg
      - name: Upload to the repository
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg
